### ISSUE TITLE
Modifier `authorized` is not implemented

### ISSUE THREAD

**Issue by nathanph** [dapphub/ds-auth#6]
Hey, I just noticed some discrepencies between the [documentation of DSAuth](https://dappsys.readthedocs.io/en/latest/ds_auth.htm) and the [implementation of DSAuth](https://github.com/dapphub/ds-auth/blob/master/src/auth.sol):
1. The [documentation](https://dappsys.readthedocs.io/en/latest/ds_auth.html#modifier-authorized) states that there would be a `modifier authorized`, but that doesn't seem to exist in the [implementation](https://github.com/dapphub/ds-auth/blob/master/src/auth.sol).
2. The [documentation](https://dappsys.readthedocs.io/en/latest/ds_auth.html#modifier-authorized) suggests that `modifer authorized` would would accept a single argument of type `bytes4`, but the examples show an argument of type `string`.

My suggestion is to overload authorized to accept types of both `string` and `bytes4`:
```js
// This can be used with static strings.
modifier authorized (string _action) 
{
    assert(isAuthorized(msg.sender, bytes4(sha3(_action))));
    _;
}

// This should be used with dynamic strings.
// The caller will have to manually generate a signature, e.g., `bytes4(sha3(stringVar))`                                                            
modifier authorized (bytes4 _sig) 
{
    assert(isAuthorized(msg.sender, _sig));
    _;
}
```

**Comment by nathanph** [comment]
Scratch that, modifiers can't be overloaded, needs to be one or the other.

**Comment by rainbreak** [comment]
@nathanph thanks for this. We actually removed `authorized` but didn't update the readme, which I'm doing now.

**Comment by nathanph** [comment]
Ah yes! There's always option 3, update the docs. 😂 

Thanks @rainbreak!

**Comment by nmushegian** [comment]
@nathanph We using `authorized` is a bit of an anti-pattern, use `auth` and something like https://github.com/dapphub/ds-guard or https://github.com/dapphub/ds-roles if you want groupings
